import type { RankDefinition } from '../../../shared/types';

// 3x3 world record is ~3.13s as of 2024
// Tiers are defined based on WR proportions

export const rankDefinitions: RankDefinition[] = [
  {
    puzzleKey: '2x2',
    tiers: [
      {
        grade: 'SSS',
        label: 'World Record Class',
        minTime: 0,
        maxTime: 2000,
        color: '#FFD700',
        bgColor: '#3D3000',
        description: 'Approaching world record territory',
      },
      {
        grade: 'SS',
        label: 'Competition Elite',
        minTime: 2000,
        maxTime: 5000,
        color: '#C0C0C0',
        bgColor: '#2A2A2A',
        description: 'Top-level competitive speed',
      },
      {
        grade: 'S',
        label: 'Advanced Speedcuber',
        minTime: 5000,
        maxTime: 10000,
        color: '#00FFFF',
        bgColor: '#003333',
        description: 'Highly skilled speedcuber',
      },
      {
        grade: 'A',
        label: 'Speedcuber',
        minTime: 10000,
        maxTime: 20000,
        color: '#00CC00',
        bgColor: '#003300',
        description: 'Solid speedcubing ability',
      },
      {
        grade: 'B',
        label: 'Intermediate',
        minTime: 20000,
        maxTime: 60000,
        color: '#4488FF',
        bgColor: '#001133',
        description: 'Improving solver',
      },
      {
        grade: 'C',
        label: 'Casual Solver',
        minTime: 60000,
        maxTime: 180000,
        color: '#AA44FF',
        bgColor: '#220033',
        description: 'Casual solving pace',
      },
      {
        grade: 'D',
        label: 'Beginner',
        minTime: 180000,
        maxTime: 600000,
        color: '#FF8800',
        bgColor: '#331A00',
        description: 'Learning the basics',
      },
      {
        grade: 'E',
        label: 'Novice',
        minTime: 600000,
        maxTime: null,
        color: '#888888',
        bgColor: '#1A1A1A',
        description: 'Just getting started',
      },
    ],
  },
  {
    puzzleKey: '3x3',
    tiers: [
      {
        grade: 'SSS',
        label: 'World Record Class',
        minTime: 0,
        maxTime: 10000,
        color: '#FFD700',
        bgColor: '#3D3000',
        description: 'Approaching world record territory',
      },
      {
        grade: 'SS',
        label: 'Competition Elite',
        minTime: 10000,
        maxTime: 20000,
        color: '#C0C0C0',
        bgColor: '#2A2A2A',
        description: 'Top-level competitive speed',
      },
      {
        grade: 'S',
        label: 'Advanced Speedcuber',
        minTime: 20000,
        maxTime: 45000,
        color: '#00FFFF',
        bgColor: '#003333',
        description: 'Highly skilled speedcuber',
      },
      {
        grade: 'A',
        label: 'Speedcuber',
        minTime: 45000,
        maxTime: 120000,
        color: '#00CC00',
        bgColor: '#003300',
        description: 'Solid speedcubing ability',
      },
      {
        grade: 'B',
        label: 'Intermediate',
        minTime: 120000,
        maxTime: 300000,
        color: '#4488FF',
        bgColor: '#001133',
        description: 'Improving solver',
      },
      {
        grade: 'C',
        label: 'Casual Solver',
        minTime: 300000,
        maxTime: 900000,
        color: '#AA44FF',
        bgColor: '#220033',
        description: 'Casual solving pace',
      },
      {
        grade: 'D',
        label: 'Beginner',
        minTime: 900000,
        maxTime: 1800000,
        color: '#FF8800',
        bgColor: '#331A00',
        description: 'Learning the basics',
      },
      {
        grade: 'E',
        label: 'Novice',
        minTime: 1800000,
        maxTime: null,
        color: '#888888',
        bgColor: '#1A1A1A',
        description: 'Just getting started',
      },
    ],
  },
  {
    puzzleKey: '4x4',
    tiers: [
      {
        grade: 'SSS',
        label: 'World Record Class',
        minTime: 0,
        maxTime: 25000,
        color: '#FFD700',
        bgColor: '#3D3000',
        description: 'Approaching world record territory',
      },
      {
        grade: 'SS',
        label: 'Competition Elite',
        minTime: 25000,
        maxTime: 60000,
        color: '#C0C0C0',
        bgColor: '#2A2A2A',
        description: 'Top-level competitive speed',
      },
      {
        grade: 'S',
        label: 'Advanced Speedcuber',
        minTime: 60000,
        maxTime: 120000,
        color: '#00FFFF',
        bgColor: '#003333',
        description: 'Highly skilled speedcuber',
      },
      {
        grade: 'A',
        label: 'Speedcuber',
        minTime: 120000,
        maxTime: 300000,
        color: '#00CC00',
        bgColor: '#003300',
        description: 'Solid speedcubing ability',
      },
      {
        grade: 'B',
        label: 'Intermediate',
        minTime: 300000,
        maxTime: 600000,
        color: '#4488FF',
        bgColor: '#001133',
        description: 'Improving solver',
      },
      {
        grade: 'C',
        label: 'Casual Solver',
        minTime: 600000,
        maxTime: 1800000,
        color: '#AA44FF',
        bgColor: '#220033',
        description: 'Casual solving pace',
      },
      {
        grade: 'D',
        label: 'Beginner',
        minTime: 1800000,
        maxTime: 3600000,
        color: '#FF8800',
        bgColor: '#331A00',
        description: 'Learning the basics',
      },
      {
        grade: 'E',
        label: 'Novice',
        minTime: 3600000,
        maxTime: null,
        color: '#888888',
        bgColor: '#1A1A1A',
        description: 'Just getting started',
      },
    ],
  },
  {
    puzzleKey: '5x5',
    tiers: [
      {
        grade: 'SSS',
        label: 'World Record Class',
        minTime: 0,
        maxTime: 40000,
        color: '#FFD700',
        bgColor: '#3D3000',
        description: 'Approaching world record territory',
      },
      {
        grade: 'SS',
        label: 'Competition Elite',
        minTime: 40000,
        maxTime: 90000,
        color: '#C0C0C0',
        bgColor: '#2A2A2A',
        description: 'Top-level competitive speed',
      },
      {
        grade: 'S',
        label: 'Advanced Speedcuber',
        minTime: 90000,
        maxTime: 180000,
        color: '#00FFFF',
        bgColor: '#003333',
        description: 'Highly skilled speedcuber',
      },
      {
        grade: 'A',
        label: 'Speedcuber',
        minTime: 180000,
        maxTime: 420000,
        color: '#00CC00',
        bgColor: '#003300',
        description: 'Solid speedcubing ability',
      },
      {
        grade: 'B',
        label: 'Intermediate',
        minTime: 420000,
        maxTime: 900000,
        color: '#4488FF',
        bgColor: '#001133',
        description: 'Improving solver',
      },
      {
        grade: 'C',
        label: 'Casual Solver',
        minTime: 900000,
        maxTime: 2700000,
        color: '#AA44FF',
        bgColor: '#220033',
        description: 'Casual solving pace',
      },
      {
        grade: 'D',
        label: 'Beginner',
        minTime: 2700000,
        maxTime: 5400000,
        color: '#FF8800',
        bgColor: '#331A00',
        description: 'Learning the basics',
      },
      {
        grade: 'E',
        label: 'Novice',
        minTime: 5400000,
        maxTime: null,
        color: '#888888',
        bgColor: '#1A1A1A',
        description: 'Just getting started',
      },
    ],
  },
  {
    puzzleKey: '6x6',
    tiers: [
      {
        grade: 'SSS',
        label: 'World Record Class',
        minTime: 0,
        maxTime: 70000,
        color: '#FFD700',
        bgColor: '#3D3000',
        description: 'Approaching world record territory',
      },
      {
        grade: 'SS',
        label: 'Competition Elite',
        minTime: 70000,
        maxTime: 150000,
        color: '#C0C0C0',
        bgColor: '#2A2A2A',
        description: 'Top-level competitive speed',
      },
      {
        grade: 'S',
        label: 'Advanced Speedcuber',
        minTime: 150000,
        maxTime: 300000,
        color: '#00FFFF',
        bgColor: '#003333',
        description: 'Highly skilled speedcuber',
      },
      {
        grade: 'A',
        label: 'Speedcuber',
        minTime: 300000,
        maxTime: 720000,
        color: '#00CC00',
        bgColor: '#003300',
        description: 'Solid speedcubing ability',
      },
      {
        grade: 'B',
        label: 'Intermediate',
        minTime: 720000,
        maxTime: 1500000,
        color: '#4488FF',
        bgColor: '#001133',
        description: 'Improving solver',
      },
      {
        grade: 'C',
        label: 'Casual Solver',
        minTime: 1500000,
        maxTime: 4500000,
        color: '#AA44FF',
        bgColor: '#220033',
        description: 'Casual solving pace',
      },
      {
        grade: 'D',
        label: 'Beginner',
        minTime: 4500000,
        maxTime: 9000000,
        color: '#FF8800',
        bgColor: '#331A00',
        description: 'Learning the basics',
      },
      {
        grade: 'E',
        label: 'Novice',
        minTime: 9000000,
        maxTime: null,
        color: '#888888',
        bgColor: '#1A1A1A',
        description: 'Just getting started',
      },
    ],
  },
  {
    puzzleKey: '7x7',
    tiers: [
      {
        grade: 'SSS',
        label: 'World Record Class',
        minTime: 0,
        maxTime: 110000,
        color: '#FFD700',
        bgColor: '#3D3000',
        description: 'Approaching world record territory',
      },
      {
        grade: 'SS',
        label: 'Competition Elite',
        minTime: 110000,
        maxTime: 240000,
        color: '#C0C0C0',
        bgColor: '#2A2A2A',
        description: 'Top-level competitive speed',
      },
      {
        grade: 'S',
        label: 'Advanced Speedcuber',
        minTime: 240000,
        maxTime: 480000,
        color: '#00FFFF',
        bgColor: '#003333',
        description: 'Highly skilled speedcuber',
      },
      {
        grade: 'A',
        label: 'Speedcuber',
        minTime: 480000,
        maxTime: 1200000,
        color: '#00CC00',
        bgColor: '#003300',
        description: 'Solid speedcubing ability',
      },
      {
        grade: 'B',
        label: 'Intermediate',
        minTime: 1200000,
        maxTime: 2400000,
        color: '#4488FF',
        bgColor: '#001133',
        description: 'Improving solver',
      },
      {
        grade: 'C',
        label: 'Casual Solver',
        minTime: 2400000,
        maxTime: 7200000,
        color: '#AA44FF',
        bgColor: '#220033',
        description: 'Casual solving pace',
      },
      {
        grade: 'D',
        label: 'Beginner',
        minTime: 7200000,
        maxTime: 14400000,
        color: '#FF8800',
        bgColor: '#331A00',
        description: 'Learning the basics',
      },
      {
        grade: 'E',
        label: 'Novice',
        minTime: 14400000,
        maxTime: null,
        color: '#888888',
        bgColor: '#1A1A1A',
        description: 'Just getting started',
      },
    ],
  },
];

export const getRankDefinition = (puzzleKey: string): RankDefinition | undefined =>
  rankDefinitions.find((d) => d.puzzleKey === puzzleKey);
